/* Wave-4 preview data (29 leads). Auto-generated by /tmp/opencode/gen-wave4.js */

module.exports = [
  {
    "slug": "h-tex-clean",
    "name": "H-Tex Clean",
    "industry": "Cleaning",
    "area": "Houston, TX",
    "phone": "(832) 714-0212",
    "phoneLink": "tel:+18327140212",
    "brand": {
      "dark": "#231420",
      "mid": "#382338",
      "accent": "#d0617d",
      "accent2": "#e8ae7a",
      "light": "#faf4f3"
    },
    "kicker": "Houston Texas cleaning on a schedule you can rely on",
    "headline": "A clean home, on a schedule that holds",
    "sub": "The current site is a thin template with generic stock photos and no booking path — a credibility gap for a cleaning company that keeps real houses. This concept gives H-Tex a booking-first homepage with plan pricing and real proof.",
    "heroTags": [
      "Same cleaner",
      "Bonded & insured",
      "5.0-rated"
    ],
    "ctaPrimary": {
      "label": "Call (832) 714-0212",
      "href": "tel:+18327140212"
    },
    "trust": [
      {
        "n": "Houston",
        "l": "Trusted"
      },
      {
        "n": "Recurring",
        "l": "Plans"
      },
      {
        "n": "Online",
        "l": "Booking"
      },
      {
        "n": "Bonded",
        "l": "& insured"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Recurring plans",
        "d": "Weekly, bi-weekly or monthly plans with the same trusted cleaner every visit."
      },
      {
        "t": "Deep cleans",
        "d": "Move-in, move-out and seasonal deep cleans booked online in minutes."
      },
      {
        "t": "Move-out / move-in",
        "d": "Tenant-turnover cleans on a schedule landlords can actually rely on."
      },
      {
        "t": "Commercial",
        "d": "Offices and storefronts cleaned after hours on a fixed plan."
      }
    ],
    "gallery": {
      "title": "The trust section a cleaner needs",
      "sub": "Before / after rooms organized by service — real photos and checklists at build.",
      "items": [
        "Weekly plan — kitchen & baths",
        "Move-out deep clean",
        "Deep clean before/after",
        "Commercial after-hours"
      ]
    },
    "finance": {
      "title": "Pricing that says what it costs",
      "sub": "A section that states rates up front so a quote never has to be a phone call.",
      "points": [
        "Flat per-visit or monthly pricing",
        "First-visit guarantee",
        "Holds & move-out specials"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Houston, TX review.)",
    "proofLine": "This is a concept homepage for H-Tex Clean. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "kb-clean-houston",
    "name": "KB Clean Houston",
    "industry": "Cleaning",
    "area": "Houston, TX",
    "phone": "713-408-5558",
    "phoneLink": "tel:+17134085558",
    "brand": {
      "dark": "#14261c",
      "mid": "#2c4a35",
      "accent": "#7fb069",
      "accent2": "#d9a441",
      "light": "#f4f1ea"
    },
    "kicker": "Houston Texas cleaning on a schedule you can rely on",
    "headline": "A clean home, on a schedule that holds",
    "sub": "Placeholder copy and a personal-email booking path make the service look smaller than it is. This concept gives KB Clean a real homepage: plan pricing on the first screen, online booking, and trust that matches the work.",
    "heroTags": [
      "Same cleaner",
      "Bonded & insured",
      "5.0-rated"
    ],
    "ctaPrimary": {
      "label": "Call 713-408-5558",
      "href": "tel:+17134085558"
    },
    "trust": [
      {
        "n": "Houston",
        "l": "Owned"
      },
      {
        "n": "Same",
        "l": "Cleaner"
      },
      {
        "n": "Plan",
        "l": "Pricing"
      },
      {
        "n": "Online",
        "l": "Booking"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Recurring plans",
        "d": "Weekly, bi-weekly or monthly plans with the same trusted cleaner every visit."
      },
      {
        "t": "Deep cleans",
        "d": "Move-in, move-out and seasonal deep cleans booked online in minutes."
      },
      {
        "t": "Move-out / move-in",
        "d": "Tenant-turnover cleans on a schedule landlords can actually rely on."
      },
      {
        "t": "Commercial",
        "d": "Offices and storefronts cleaned after hours on a fixed plan."
      }
    ],
    "gallery": {
      "title": "The trust section a cleaner needs",
      "sub": "Before / after rooms organized by service — real photos and checklists at build.",
      "items": [
        "Weekly plan — kitchen & baths",
        "Move-out deep clean",
        "Deep clean before/after",
        "Commercial after-hours"
      ]
    },
    "finance": {
      "title": "Pricing that says what it costs",
      "sub": "A section that states rates up front so a quote never has to be a phone call.",
      "points": [
        "Flat per-visit or monthly pricing",
        "First-visit guarantee",
        "Holds & move-out specials"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Houston, TX review.)",
    "proofLine": "This is a concept homepage for KB Clean Houston. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "pat-and-dad-s-pool-service",
    "name": "Pat & Dad's Pool Service",
    "industry": "Pool Cleaning",
    "area": "Katy, TX",
    "phone": "281-923-6755",
    "phoneLink": "tel:+12819236755",
    "brand": {
      "dark": "#0f2a22",
      "mid": "#1c4a3c",
      "accent": "#4fdcae",
      "accent2": "#f2c14e",
      "light": "#eff7f3"
    },
    "kicker": "Katy Texas pool care on a fixed plan",
    "headline": "A clean pool, on a fixed weekly plan",
    "sub": "A bare one-pager with an AOL address — the roadside sign equivalent of a pool business. This concept gives Pat & Dad a homepage with weekly plan pricing, a green-to-clear rescue section and a gallery that shows the work.",
    "heroTags": [
      "Weekly service",
      "Flat monthly",
      "Green-to-clear"
    ],
    "ctaPrimary": {
      "label": "Call 281-923-6755",
      "href": "tel:+12819236755"
    },
    "trust": [
      {
        "n": "Katy",
        "l": "Pools"
      },
      {
        "n": "Weekly",
        "l": "Plans"
      },
      {
        "n": "Green",
        "l": "-to-clear"
      },
      {
        "n": "Local",
        "l": "Owned"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Weekly service",
        "d": "Consistent chemistry, brushing and filtering on a fixed repeat visit."
      },
      {
        "t": "Green pools",
        "d": "Green-to-clear recovery programs priced before the first shock."
      },
      {
        "t": "Repairs & equipment",
        "d": "Pumps, filters and heaters diagnosed and quoted before work starts."
      },
      {
        "t": "Seasonal open/close",
        "d": "Spring opens and winter closes on a schedule you can rely on."
      }
    ],
    "gallery": {
      "title": "The clean-pool gallery that sells it",
      "sub": "Pools documented before and after service — real photos and care notes at build.",
      "items": [
        "Weekly service — before/after",
        "Green-to-clear rescue",
        "Tile & waterline detail",
        "Equipment room refresh"
      ]
    },
    "finance": {
      "title": "Plan pricing, on the record",
      "sub": "A section that shows monthly costs so the budget question never stops a signup.",
      "points": [
        "Flat monthly plan pricing",
        "No long-term lock-in",
        "Equipment repairs quoted first"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Katy, TX review.)",
    "proofLine": "This is a concept homepage for Pat & Dad's Pool Service. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "katy-pool-cleaners",
    "name": "Katy Pool Cleaners",
    "industry": "Pool Cleaning",
    "area": "Katy, TX",
    "phone": "832-464-6645",
    "phoneLink": "tel:+18324646645",
    "brand": {
      "dark": "#161a14",
      "mid": "#283026",
      "accent": "#a5b37a",
      "accent2": "#e3c98a",
      "light": "#f6f5ef"
    },
    "kicker": "Katy Texas pool care on a fixed plan",
    "headline": "A clean pool, on a fixed weekly plan",
    "sub": "A thin, DIY-feel page with a gmail contact undersells the pool service. This concept rebuilds it around flat weekly plan pricing, a rescue section and a before/after gallery that closes signups.",
    "heroTags": [
      "Weekly service",
      "Flat monthly",
      "Green-to-clear"
    ],
    "ctaPrimary": {
      "label": "Call 832-464-6645",
      "href": "tel:+18324646645"
    },
    "trust": [
      {
        "n": "Katy",
        "l": "Local"
      },
      {
        "n": "Flat",
        "l": "Monthly"
      },
      {
        "n": "Weekly",
        "l": "Service"
      },
      {
        "n": "Before",
        "l": "/after proof"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Weekly service",
        "d": "Consistent chemistry, brushing and filtering on a fixed repeat visit."
      },
      {
        "t": "Green pools",
        "d": "Green-to-clear recovery programs priced before the first shock."
      },
      {
        "t": "Repairs & equipment",
        "d": "Pumps, filters and heaters diagnosed and quoted before work starts."
      },
      {
        "t": "Seasonal open/close",
        "d": "Spring opens and winter closes on a schedule you can rely on."
      }
    ],
    "gallery": {
      "title": "The clean-pool gallery that sells it",
      "sub": "Pools documented before and after service — real photos and care notes at build.",
      "items": [
        "Weekly service — before/after",
        "Green-to-clear rescue",
        "Tile & waterline detail",
        "Equipment room refresh"
      ]
    },
    "finance": {
      "title": "Plan pricing, on the record",
      "sub": "A section that shows monthly costs so the budget question never stops a signup.",
      "points": [
        "Flat monthly plan pricing",
        "No long-term lock-in",
        "Equipment repairs quoted first"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Katy, TX review.)",
    "proofLine": "This is a concept homepage for Katy Pool Cleaners. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "mcdaddy-s-pressure-washing-and-carpet-cleaning",
    "name": "McDaddy's Pressure Washing & Carpet Cleaning",
    "industry": "Pressure Washing",
    "area": "Pearland, TX",
    "phone": "832-725-4520",
    "phoneLink": "tel:+18327254520",
    "brand": {
      "dark": "#221711",
      "mid": "#3b2a1c",
      "accent": "#e0a53e",
      "accent2": "#7fb069",
      "light": "#faf5ec"
    },
    "kicker": "Pearland Texas pressure washing, flat rate per surface",
    "headline": "Clean like it was day one",
    "sub": "Pressure washing sells on before/after proof, and the current site has almost none — just a rough template and an AOL address. This concept gives McDaddy a quote-from-photos homepage with a before/after gallery on the first screen.",
    "heroTags": [
      "Flat rate",
      "Soft-wash safe",
      "Insured"
    ],
    "ctaPrimary": {
      "label": "Call 832-725-4520",
      "href": "tel:+18327254520"
    },
    "trust": [
      {
        "n": "Quote",
        "l": "from photos"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Flat",
        "l": "rates"
      },
      {
        "n": "Pearland",
        "l": "Local"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Driveway & walkways",
        "d": "Cleaning that makes the approach look new again."
      },
      {
        "t": "House / siding washing",
        "d": "Soft-wash methods that protect paint and windows."
      },
      {
        "t": "Roof cleaning",
        "d": "Mildew and staining removal without pressure damage."
      },
      {
        "t": "Paver sealing",
        "d": "Clean first, then seal — so it stays looking sold."
      }
    ],
    "gallery": {
      "title": "The before/after reel that sells it",
      "sub": "Surfaces cleaned and sealed — real before/after sets at build.",
      "items": [
        "Driveway reveal",
        "Siding soft-wash",
        "Roof stain removal",
        "Paver seal — before/after"
      ]
    },
    "finance": {
      "title": "Flat rate, quoted from photos",
      "sub": "A section that answers the cost question before the first phone call.",
      "points": [
        "Flat rate per surface",
        "Quote from photos, in writing",
        "Satisfaction touch-up pass"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Pearland, TX review.)",
    "proofLine": "This is a concept homepage for McDaddy's Pressure Washing & Carpet Cleaning. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "alex-collision-center",
    "name": "Alex Collision Center",
    "industry": "Auto Body",
    "area": "Houston, TX",
    "phone": "(281) 506-8530",
    "phoneLink": "tel:+12815068530",
    "brand": {
      "dark": "#12203a",
      "mid": "#1f3760",
      "accent": "#d98f6a",
      "accent2": "#aebfd9",
      "light": "#f1f4fa"
    },
    "kicker": "Houston Texas collision & paint, answered by people you can call",
    "headline": "Fixed up right, or it does not leave the shop",
    "sub": "An old page with a Yahoo address and no online estimate path leaves money on the table when people choose a shop on their phone. This concept gives Alex a photo-estimate flow, insurance handling and a gallery that closes the drop.",
    "heroTags": [
      "Written estimates",
      "Insurance handled",
      "Family-run"
    ],
    "ctaPrimary": {
      "label": "Call (281) 506-8530",
      "href": "tel:+12815068530"
    },
    "trust": [
      {
        "n": "24h",
        "l": "Photo estimate"
      },
      {
        "n": "Insurance",
        "l": "Handled"
      },
      {
        "n": "Houston",
        "l": "Shop"
      },
      {
        "n": "Written",
        "l": "Quotes"
      }
    ],
    "servicesTitle": "What the rebuilt site leads with",
    "services": [
      {
        "t": "Collision repair",
        "d": "Factory-spec repairs with a written estimate before any work starts or a single part is ordered."
      },
      {
        "t": "Paint & color match",
        "d": "Booth-finished paint matched to the VIN so repaired panels disappear into the body."
      },
      {
        "t": "Insurance claims",
        "d": "Direct insurance handling — your estimate, supplements and parts sourced for you, not against you."
      },
      {
        "t": "24-hour estimates",
        "d": "An estimate from photos inside a day, so the insurance question never stalls the repair."
      }
    ],
    "gallery": {
      "title": "The repair gallery that closes jobs",
      "sub": "Before / after panels organized by job — real photos, scope notes and turnaround at build.",
      "items": [
        "Collision repair — 5-day turnaround",
        "Full respray, color-match detail",
        "Dent & ding package",
        "Insurance estimate walkthrough"
      ]
    },
    "finance": {
      "title": "Repair pricing, answered up front",
      "sub": "A section that names terms so the can-I-afford-it question never stops a repair.",
      "points": [
        "Estimates in writing before work starts",
        "Insurance claims handled direct",
        "Payment plans where approved"
      ]
    },
    "insurance": {
      "title": "We work with your insurance, not around it",
      "sub": "An insurance section that tells customers you write the estimate and handle the paperwork for them.",
      "points": [
        "We write the estimate and file it",
        "Supplements handled on your behalf",
        "Rental coordination where covered"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Houston, TX review.)",
    "proofLine": "This is a concept homepage for Alex Collision Center. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "kev-s-painting-service",
    "name": "Kev's Painting Service",
    "industry": "Painting",
    "area": "Conroe, TX",
    "phone": "(936) 228-8062",
    "phoneLink": "tel:+19362288062",
    "brand": {
      "dark": "#1d1a10",
      "mid": "#36301c",
      "accent": "#d3b24a",
      "accent2": "#c96f4a",
      "light": "#f8f5ec"
    },
    "kicker": "Conroe Texas painting, quoted before the first coat",
    "headline": "A finish that looks done by a crew, not rolled by one",
    "sub": "A bare template with a gmail address shows up before the finish does. This concept gives Kev a homepage where prep-included pricing, a before/after gallery and interior/exterior service pages do the selling.",
    "heroTags": [
      "Prep included",
      "Itemized quotes",
      "Cleanup done"
    ],
    "ctaPrimary": {
      "label": "Call (936) 228-8062",
      "href": "tel:+19362288062"
    },
    "trust": [
      {
        "n": "Prep",
        "l": "included"
      },
      {
        "n": "Itemized",
        "l": "quotes"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Local",
        "l": "owned"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Interior painting",
        "d": "Two-coat consistency, cut in clean, and a walkthrough before the last check clears."
      },
      {
        "t": "Exterior painting",
        "d": "Prep-first exterior repaints with the right coatings for local weather."
      },
      {
        "t": "Cabinet & trim",
        "d": "Refinishing and cabinet repaint that look factory, not brushed."
      },
      {
        "t": "Drywall repair",
        "d": "Holes, patches and texture matched before a single coat goes on."
      }
    ],
    "gallery": {
      "title": "The finish gallery a painter needs",
      "sub": "Interior and exterior jobs documented by project — real photos and prep detail at build.",
      "items": [
        "Exterior full repaint",
        "Interior color transition",
        "Cabinet refinish close-up",
        "Drywall-repair finish"
      ]
    },
    "finance": {
      "title": "Quoted before the first coat",
      "sub": "A section that states terms so budget questions never stop an enquiry.",
      "points": [
        "Itemized estimate before work",
        "Prep included in the quote",
        "Paint brands stated up front"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Conroe, TX review.)",
    "proofLine": "This is a concept homepage for Kev's Painting Service. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "garcia-paint-and-body",
    "name": "Garcia Paint & Body",
    "industry": "Auto Body",
    "area": "Garland, TX",
    "phone": "+1 469-367-0029",
    "phoneLink": "tel:+114693670029",
    "brand": {
      "dark": "#1c1412",
      "mid": "#33241f",
      "accent": "#d1603d",
      "accent2": "#e8c06a",
      "light": "#f6f0e8"
    },
    "kicker": "Garland Texas collision & paint, answered by people you can call",
    "headline": "Fixed up right, or it does not leave the shop",
    "sub": "Filler copy and a gmail-only estimate path undersell a Garland shop. This concept gives Garcia a photo-estimate homepage, insurance handling front and center, and a repair gallery that closes the trust gap.",
    "heroTags": [
      "Written estimates",
      "Insurance handled",
      "Family-run"
    ],
    "ctaPrimary": {
      "label": "Call +1 469-367-0029",
      "href": "tel:+114693670029"
    },
    "trust": [
      {
        "n": "Garland",
        "l": "Local"
      },
      {
        "n": "Photo",
        "l": "estimates"
      },
      {
        "n": "Insurance",
        "l": "handled"
      },
      {
        "n": "Bilingual",
        "l": "EN / ES"
      }
    ],
    "servicesTitle": "What the rebuilt site leads with",
    "services": [
      {
        "t": "Collision repair",
        "d": "Factory-spec repairs with a written estimate before any work starts or a single part is ordered."
      },
      {
        "t": "Paint & color match",
        "d": "Booth-finished paint matched to the VIN so repaired panels disappear into the body."
      },
      {
        "t": "Insurance claims",
        "d": "Direct insurance handling — your estimate, supplements and parts sourced for you, not against you."
      },
      {
        "t": "24-hour estimates",
        "d": "An estimate from photos inside a day, so the insurance question never stalls the repair."
      }
    ],
    "gallery": {
      "title": "The repair gallery that closes jobs",
      "sub": "Before / after panels organized by job — real photos, scope notes and turnaround at build.",
      "items": [
        "Collision repair — 5-day turnaround",
        "Full respray, color-match detail",
        "Dent & ding package",
        "Insurance estimate walkthrough"
      ]
    },
    "finance": {
      "title": "Repair pricing, answered up front",
      "sub": "A section that names terms so the can-I-afford-it question never stops a repair.",
      "points": [
        "Estimates in writing before work starts",
        "Insurance claims handled direct",
        "Payment plans where approved"
      ]
    },
    "insurance": {
      "title": "We work with your insurance, not around it",
      "sub": "An insurance section that tells customers you write the estimate and handle the paperwork for them.",
      "points": [
        "We write the estimate and file it",
        "Supplements handled on your behalf",
        "Rental coordination where covered"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Garland, TX review.)",
    "proofLine": "This is a concept homepage for Garcia Paint & Body. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "david-johnson-plumbing",
    "name": "David Johnson Plumbing",
    "industry": "Plumbing",
    "area": "Arlington, TX",
    "phone": "817-235-3045",
    "phoneLink": "tel:+18172353045",
    "brand": {
      "dark": "#201421",
      "mid": "#3a2536",
      "accent": "#c978a8",
      "accent2": "#e3b07a",
      "light": "#faf5f7"
    },
    "kicker": "Arlington Texas plumbers who answer and show up",
    "headline": "Plumbing that shows up and gets it right",
    "sub": "A bare page with an sbcglobal.net address undersells a licensed Arlington plumber. This concept gives David Johnson flat-rate pricing pages, a 24/7 repair button and proof that reads like the license does.",
    "heroTags": [
      "24/7 emergency",
      "Up-front pricing",
      "Licensed & insured"
    ],
    "ctaPrimary": {
      "label": "Call 817-235-3045",
      "href": "tel:+18172353045"
    },
    "trust": [
      {
        "n": "1963",
        "l": "Registered"
      },
      {
        "n": "Licensed",
        "l": "TX"
      },
      {
        "n": "Flat-rate",
        "l": "pricing"
      },
      {
        "n": "24/7",
        "l": "repair line"
      }
    ],
    "servicesTitle": "Services the rebuilt site owns",
    "services": [
      {
        "t": "Emergency repair",
        "d": "A rapid-response line for burst pipes, leaks and after-hours failures."
      },
      {
        "t": "Drains & leaks",
        "d": "Diagnostics that find the real issue instead of selling a re-pipe."
      },
      {
        "t": "Water heaters",
        "d": "Sizing, install and warranty-backed tanks and tankless units."
      },
      {
        "t": "Sewer & repipes",
        "d": "Camera inspections and clear, quoted pricing before trenching starts."
      }
    ],
    "gallery": {
      "title": "The service gallery a plumber needs",
      "sub": "Work organized by job — real photos, scope notes and turnarounds at build.",
      "items": [
        "Emergency repair — same-day",
        "Water heater swap",
        "Drain line diagnostic",
        "Bathroom repipe plan"
      ]
    },
    "finance": {
      "title": "Prices, answered before the call",
      "sub": "A section that names pricing terms so cost questions never stall a service call.",
      "points": [
        "Flat-rate pricing per job",
        "Financing where offered",
        "Warranty details on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Arlington, TX review.)",
    "proofLine": "This is a concept homepage for David Johnson Plumbing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "flat-rate-plumbing-company",
    "name": "Flat Rate Plumbing Company",
    "industry": "Plumbing",
    "area": "Grand Prairie, TX",
    "phone": "(972) 641-4837",
    "phoneLink": "tel:+19726414837",
    "brand": {
      "dark": "#221711",
      "mid": "#3b2a1c",
      "accent": "#e0a53e",
      "accent2": "#7fb069",
      "light": "#faf5ec"
    },
    "kicker": "Grand Prairie Texas plumbers who answer and show up",
    "headline": "Plumbing that shows up and gets it right",
    "sub": "A business named \"Flat Rate\" deserves pricing on the homepage, not an unfinished page and an sbcglobal address. This concept puts flat-rate numbers up front, adds an emergency button and makes booking one tap.",
    "heroTags": [
      "24/7 emergency",
      "Up-front pricing",
      "Licensed & insured"
    ],
    "ctaPrimary": {
      "label": "Call (972) 641-4837",
      "href": "tel:+19726414837"
    },
    "trust": [
      {
        "n": "Flat-rate",
        "l": "by name"
      },
      {
        "n": "24/7",
        "l": "emergency"
      },
      {
        "n": "Grand",
        "l": "Prairie"
      },
      {
        "n": "Written",
        "l": "quotes"
      }
    ],
    "servicesTitle": "Services the rebuilt site owns",
    "services": [
      {
        "t": "Emergency repair",
        "d": "A rapid-response line for burst pipes, leaks and after-hours failures."
      },
      {
        "t": "Drains & leaks",
        "d": "Diagnostics that find the real issue instead of selling a re-pipe."
      },
      {
        "t": "Water heaters",
        "d": "Sizing, install and warranty-backed tanks and tankless units."
      },
      {
        "t": "Sewer & repipes",
        "d": "Camera inspections and clear, quoted pricing before trenching starts."
      }
    ],
    "gallery": {
      "title": "The service gallery a plumber needs",
      "sub": "Work organized by job — real photos, scope notes and turnarounds at build.",
      "items": [
        "Emergency repair — same-day",
        "Water heater swap",
        "Drain line diagnostic",
        "Bathroom repipe plan"
      ]
    },
    "finance": {
      "title": "Prices, answered before the call",
      "sub": "A section that names pricing terms so cost questions never stall a service call.",
      "points": [
        "Flat-rate pricing per job",
        "Financing where offered",
        "Warranty details on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Grand Prairie, TX review.)",
    "proofLine": "This is a concept homepage for Flat Rate Plumbing Company. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "juiel-s-auto-clinic",
    "name": "Juiel's Auto Clinic",
    "industry": "Auto Body",
    "area": "San Antonio, TX",
    "phone": "210.990.1999",
    "phoneLink": "tel:+12109901999",
    "brand": {
      "dark": "#161a14",
      "mid": "#283026",
      "accent": "#a5b37a",
      "accent2": "#e3c98a",
      "light": "#f6f5ef"
    },
    "kicker": "San Antonio Texas collision & paint, answered by people you can call",
    "headline": "Fixed up right, or it does not leave the shop",
    "sub": "A single static page with a gmail address is the whole web presence for a shop that needs phone traffic. This concept gives Juiel a photo-estimate flow, insurance section and a gallery that makes the shop feel real before the visit.",
    "heroTags": [
      "Written estimates",
      "Insurance handled",
      "Family-run"
    ],
    "ctaPrimary": {
      "label": "Call 210.990.1999",
      "href": "tel:+12109901999"
    },
    "trust": [
      {
        "n": "San",
        "l": "Antonio"
      },
      {
        "n": "Photo",
        "l": "estimates"
      },
      {
        "n": "Insurance",
        "l": "handled"
      },
      {
        "n": "Family",
        "l": "owned"
      }
    ],
    "servicesTitle": "What the rebuilt site leads with",
    "services": [
      {
        "t": "Collision repair",
        "d": "Factory-spec repairs with a written estimate before any work starts or a single part is ordered."
      },
      {
        "t": "Paint & color match",
        "d": "Booth-finished paint matched to the VIN so repaired panels disappear into the body."
      },
      {
        "t": "Insurance claims",
        "d": "Direct insurance handling — your estimate, supplements and parts sourced for you, not against you."
      },
      {
        "t": "24-hour estimates",
        "d": "An estimate from photos inside a day, so the insurance question never stalls the repair."
      }
    ],
    "gallery": {
      "title": "The repair gallery that closes jobs",
      "sub": "Before / after panels organized by job — real photos, scope notes and turnaround at build.",
      "items": [
        "Collision repair — 5-day turnaround",
        "Full respray, color-match detail",
        "Dent & ding package",
        "Insurance estimate walkthrough"
      ]
    },
    "finance": {
      "title": "Repair pricing, answered up front",
      "sub": "A section that names terms so the can-I-afford-it question never stops a repair.",
      "points": [
        "Estimates in writing before work starts",
        "Insurance claims handled direct",
        "Payment plans where approved"
      ]
    },
    "insurance": {
      "title": "We work with your insurance, not around it",
      "sub": "An insurance section that tells customers you write the estimate and handle the paperwork for them.",
      "points": [
        "We write the estimate and file it",
        "Supplements handled on your behalf",
        "Rental coordination where covered"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real San Antonio, TX review.)",
    "proofLine": "This is a concept homepage for Juiel's Auto Clinic. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "cardinal-contracting-and-roofing",
    "name": "Cardinal Contracting & Roofing",
    "industry": "Roofing",
    "area": "Jacksonville, FL",
    "phone": "904-303-0738",
    "phoneLink": "tel:+19043030738",
    "brand": {
      "dark": "#26120f",
      "mid": "#40201a",
      "accent": "#dd6b3f",
      "accent2": "#f0c987",
      "light": "#f8f2ea"
    },
    "kicker": "Jacksonville Florida roofing repairs and replacements",
    "headline": "A roof fixed right, in writing first",
    "sub": "A recently built template with generic stock roofing photos and a gmail address does not carry a roofing reputation. This concept gives Cardinal a storm-response homepage, insurance-first estimate flow and a work gallery homeowners believe.",
    "heroTags": [
      "Insurance help",
      "Written quotes",
      "Licensed crew"
    ],
    "ctaPrimary": {
      "label": "Call 904-303-0738",
      "href": "tel:+19043030738"
    },
    "trust": [
      {
        "n": "Jax",
        "l": "roofs"
      },
      {
        "n": "Storm",
        "l": "response"
      },
      {
        "n": "Insurance",
        "l": "help"
      },
      {
        "n": "Written",
        "l": "quotes"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Roof repair",
        "d": "Leak locating and shingle repair before further damage sets in."
      },
      {
        "t": "Roof replacement",
        "d": "Materials, warranty and timeline quoted in writing."
      },
      {
        "t": "Storm damage",
        "d": "Insurance-assisted documentation for hail and wind claims."
      },
      {
        "t": "Gutters & flashing",
        "d": "The details that keep water where it belongs."
      }
    ],
    "gallery": {
      "title": "The work album a roofer needs",
      "sub": "Repairs and replacements documented by job — real photos and warranties at build.",
      "items": [
        "Leak repair assessment",
        "Full replacement timeline",
        "Hail documentation set",
        "Gutter & flashing finish"
      ]
    },
    "finance": {
      "title": "Quoted in writing, insured",
      "sub": "A section that answers cost and insurance questions before the estimate call.",
      "points": [
        "Material + labor itemized quote",
        "Insurance documentation assistance",
        "Transferable warranty"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Jacksonville, FL review.)",
    "proofLine": "This is a concept homepage for Cardinal Contracting & Roofing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "j-and-m-pressure-washing",
    "name": "J & M Pressure Washing",
    "industry": "Pressure Washing",
    "area": "Orlando, FL",
    "phone": "(207) 607-3100",
    "phoneLink": "tel:+12076073100",
    "brand": {
      "dark": "#0e2421",
      "mid": "#1c3b36",
      "accent": "#5fc9a8",
      "accent2": "#e0b54a",
      "light": "#f2f7f4"
    },
    "kicker": "Orlando Florida pressure washing, flat rate per surface",
    "headline": "Clean like it was day one",
    "sub": "Pressure washing is a before/after business and the site shows almost none of it. This concept gives J&M a quote-from-photos homepage with a full before/after gallery, flat per-surface rates and instant booking.",
    "heroTags": [
      "Flat rate",
      "Soft-wash safe",
      "Insured"
    ],
    "ctaPrimary": {
      "label": "Call (207) 607-3100",
      "href": "tel:+12076073100"
    },
    "trust": [
      {
        "n": "Orlando",
        "l": "local"
      },
      {
        "n": "Quote",
        "l": "from photos"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Flat",
        "l": "rates"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Driveway & walkways",
        "d": "Cleaning that makes the approach look new again."
      },
      {
        "t": "House / siding washing",
        "d": "Soft-wash methods that protect paint and windows."
      },
      {
        "t": "Roof cleaning",
        "d": "Mildew and staining removal without pressure damage."
      },
      {
        "t": "Paver sealing",
        "d": "Clean first, then seal — so it stays looking sold."
      }
    ],
    "gallery": {
      "title": "The before/after reel that sells it",
      "sub": "Surfaces cleaned and sealed — real before/after sets at build.",
      "items": [
        "Driveway reveal",
        "Siding soft-wash",
        "Roof stain removal",
        "Paver seal — before/after"
      ]
    },
    "finance": {
      "title": "Flat rate, quoted from photos",
      "sub": "A section that answers the cost question before the first phone call.",
      "points": [
        "Flat rate per surface",
        "Quote from photos, in writing",
        "Satisfaction touch-up pass"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Orlando, FL review.)",
    "proofLine": "This is a concept homepage for J & M Pressure Washing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "j-brother-s-garage-door",
    "name": "J Brother's Garage Door",
    "industry": "Garage Doors",
    "area": "Orlando, FL",
    "phone": "(407) 819-4466",
    "phoneLink": "tel:+14078194466",
    "brand": {
      "dark": "#12203a",
      "mid": "#1f3760",
      "accent": "#d98f6a",
      "accent2": "#aebfd9",
      "light": "#f1f4fa"
    },
    "kicker": "Orlando Florida garage doors, serviced same-day",
    "headline": "Doors that open, repaired the same day",
    "sub": "A bare template page can't sell same-day garage door service — that is a phone-and-book business. This concept gives J Brother a 24/7 door-locked button, same-day booking and an install gallery that earns the emergency call.",
    "heroTags": [
      "Same-day repair",
      "Written quotes",
      "5.0-rated"
    ],
    "ctaPrimary": {
      "label": "Call (407) 819-4466",
      "href": "tel:+14078194466"
    },
    "trust": [
      {
        "n": "Same-day",
        "l": "repair"
      },
      {
        "n": "24/7",
        "l": "door-locked"
      },
      {
        "n": "Written",
        "l": "quotes"
      },
      {
        "n": "Orlando",
        "l": "local"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Garage door repair",
        "d": "Cables, springs, rollers and openers repaired same-day where possible."
      },
      {
        "t": "New door installs",
        "d": "Sightline and material guidance with a clean, warrantied install."
      },
      {
        "t": "Opener service",
        "d": "Programming and repair across all major motor brands."
      },
      {
        "t": "Emergency service",
        "d": "Stuck-door and security repair when the door will not close or open."
      }
    ],
    "gallery": {
      "title": "The install gallery a door site needs",
      "sub": "Doors and repairs documented by job — real photos and warranties at build.",
      "items": [
        "Spring & cable service",
        "New door install",
        "Opener programming",
        "Emergency door repair"
      ]
    },
    "finance": {
      "title": "Pricing, on the record",
      "sub": "A section that states terms so a door quote never surprises anyone.",
      "points": [
        "Same-day quotes where possible",
        "Written price before install",
        "Warranty on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Orlando, FL review.)",
    "proofLine": "This is a concept homepage for J Brother's Garage Door. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "schick-roofing",
    "name": "Schick Roofing",
    "industry": "Roofing",
    "area": "Orlando, FL",
    "phone": "(407) 749-0808",
    "phoneLink": "tel:+14077490808",
    "brand": {
      "dark": "#1c1412",
      "mid": "#33241f",
      "accent": "#d1603d",
      "accent2": "#e8c06a",
      "light": "#f6f0e8"
    },
    "kicker": "Orlando Florida roofing repairs and replacements",
    "headline": "A roof fixed right, in writing first",
    "sub": "A dated page with no storm paths undersells a real roofing operation. This concept gives Schick a leadership-style homepage: written quotes, an insurance-first storm flow and work proof before the estimate call.",
    "heroTags": [
      "Insurance help",
      "Written quotes",
      "Licensed crew"
    ],
    "ctaPrimary": {
      "label": "Call (407) 749-0808",
      "href": "tel:+14077490808"
    },
    "trust": [
      {
        "n": "Orlando",
        "l": "roofs"
      },
      {
        "n": "Storm",
        "l": "response"
      },
      {
        "n": "Written",
        "l": "quotes"
      },
      {
        "n": "Insurance",
        "l": "help"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Roof repair",
        "d": "Leak locating and shingle repair before further damage sets in."
      },
      {
        "t": "Roof replacement",
        "d": "Materials, warranty and timeline quoted in writing."
      },
      {
        "t": "Storm damage",
        "d": "Insurance-assisted documentation for hail and wind claims."
      },
      {
        "t": "Gutters & flashing",
        "d": "The details that keep water where it belongs."
      }
    ],
    "gallery": {
      "title": "The work album a roofer needs",
      "sub": "Repairs and replacements documented by job — real photos and warranties at build.",
      "items": [
        "Leak repair assessment",
        "Full replacement timeline",
        "Hail documentation set",
        "Gutter & flashing finish"
      ]
    },
    "finance": {
      "title": "Quoted in writing, insured",
      "sub": "A section that answers cost and insurance questions before the estimate call.",
      "points": [
        "Material + labor itemized quote",
        "Insurance documentation assistance",
        "Transferable warranty"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Orlando, FL review.)",
    "proofLine": "This is a concept homepage for Schick Roofing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "burnes-roofing-company-llc",
    "name": "Burnes Roofing Company LLC",
    "industry": "Roofing",
    "area": "Orlando, FL",
    "phone": "407-446-9290",
    "phoneLink": "tel:+14074469290",
    "brand": {
      "dark": "#1d1a10",
      "mid": "#36301c",
      "accent": "#d3b24a",
      "accent2": "#c96f4a",
      "light": "#f8f5ec"
    },
    "kicker": "Orlando Florida roofing repairs and replacements",
    "headline": "A roof fixed right, in writing first",
    "sub": "An unfinished, café-era page with a gmail address presents \"real people roofing\" as smaller than it is. This concept gives Burnes a current, storm-ready homepage with written quotes and before/after work proof.",
    "heroTags": [
      "Insurance help",
      "Written quotes",
      "Licensed crew"
    ],
    "ctaPrimary": {
      "label": "Call 407-446-9290",
      "href": "tel:+14074469290"
    },
    "trust": [
      {
        "n": "Orlando",
        "l": "roofers"
      },
      {
        "n": "Written",
        "l": "quotes"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Storm",
        "l": "ready"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Roof repair",
        "d": "Leak locating and shingle repair before further damage sets in."
      },
      {
        "t": "Roof replacement",
        "d": "Materials, warranty and timeline quoted in writing."
      },
      {
        "t": "Storm damage",
        "d": "Insurance-assisted documentation for hail and wind claims."
      },
      {
        "t": "Gutters & flashing",
        "d": "The details that keep water where it belongs."
      }
    ],
    "gallery": {
      "title": "The work album a roofer needs",
      "sub": "Repairs and replacements documented by job — real photos and warranties at build.",
      "items": [
        "Leak repair assessment",
        "Full replacement timeline",
        "Hail documentation set",
        "Gutter & flashing finish"
      ]
    },
    "finance": {
      "title": "Quoted in writing, insured",
      "sub": "A section that answers cost and insurance questions before the estimate call.",
      "points": [
        "Material + labor itemized quote",
        "Insurance documentation assistance",
        "Transferable warranty"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Orlando, FL review.)",
    "proofLine": "This is a concept homepage for Burnes Roofing Company LLC. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "carmody-lake-plumbing",
    "name": "Carmody Lake Plumbing",
    "industry": "Plumbing",
    "area": "Lakewood, CO",
    "phone": "720-619-5678",
    "phoneLink": "tel:+17206195678",
    "brand": {
      "dark": "#26120f",
      "mid": "#40201a",
      "accent": "#dd6b3f",
      "accent2": "#f0c987",
      "light": "#f8f2ea"
    },
    "kicker": "Lakewood Colorado plumbers who answer and show up",
    "headline": "Plumbing that shows up and gets it right",
    "sub": "A thin gmail-contact template for a plumbing company in cold-country territory undersells the emergency side of the business. This concept gives Carmody Lake a 24/7 button, flat-rate pages and proof that reads like a licensed local plumber.",
    "heroTags": [
      "24/7 emergency",
      "Up-front pricing",
      "Licensed & insured"
    ],
    "ctaPrimary": {
      "label": "Call 720-619-5678",
      "href": "tel:+17206195678"
    },
    "trust": [
      {
        "n": "Lakewood",
        "l": "CO"
      },
      {
        "n": "24/7",
        "l": "emergency"
      },
      {
        "n": "Flat-rate",
        "l": "pricing"
      },
      {
        "n": "Licensed",
        "l": "& insured"
      }
    ],
    "servicesTitle": "Services the rebuilt site owns",
    "services": [
      {
        "t": "Emergency repair",
        "d": "A rapid-response line for burst pipes, leaks and after-hours failures."
      },
      {
        "t": "Drains & leaks",
        "d": "Diagnostics that find the real issue instead of selling a re-pipe."
      },
      {
        "t": "Water heaters",
        "d": "Sizing, install and warranty-backed tanks and tankless units."
      },
      {
        "t": "Sewer & repipes",
        "d": "Camera inspections and clear, quoted pricing before trenching starts."
      }
    ],
    "gallery": {
      "title": "The service gallery a plumber needs",
      "sub": "Work organized by job — real photos, scope notes and turnarounds at build.",
      "items": [
        "Emergency repair — same-day",
        "Water heater swap",
        "Drain line diagnostic",
        "Bathroom repipe plan"
      ]
    },
    "finance": {
      "title": "Prices, answered before the call",
      "sub": "A section that names pricing terms so cost questions never stall a service call.",
      "points": [
        "Flat-rate pricing per job",
        "Financing where offered",
        "Warranty details on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Lakewood, CO review.)",
    "proofLine": "This is a concept homepage for Carmody Lake Plumbing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "tim-breault-plumbing",
    "name": "Tim Breault Plumbing",
    "industry": "Plumbing",
    "area": "Charlotte, NC",
    "phone": "(704) 201-4695",
    "phoneLink": "tel:+17042014695",
    "brand": {
      "dark": "#13280f",
      "mid": "#214619",
      "accent": "#8bc34a",
      "accent2": "#f2a65a",
      "light": "#f4f7ef"
    },
    "kicker": "Charlotte North Carolina plumbers who answer and show up",
    "headline": "Plumbing that shows up and gets it right",
    "sub": "The site is functional but anonymous: a gmail address and no story, even though the company has been family-run since 1982. This concept gives Breault a homepage where the legacy shows, pricing is answered, and booking reaches a real phone.",
    "heroTags": [
      "24/7 emergency",
      "Up-front pricing",
      "Licensed & insured"
    ],
    "ctaPrimary": {
      "label": "Call (704) 201-4695",
      "href": "tel:+17042014695"
    },
    "trust": [
      {
        "n": "1982",
        "l": "Family owned"
      },
      {
        "n": "Charlotte",
        "l": "NC"
      },
      {
        "n": "Flat-rate",
        "l": "pricing"
      },
      {
        "n": "Owner",
        "l": "on the phone"
      }
    ],
    "servicesTitle": "Services the rebuilt site owns",
    "services": [
      {
        "t": "Emergency repair",
        "d": "A rapid-response line for burst pipes, leaks and after-hours failures."
      },
      {
        "t": "Drains & leaks",
        "d": "Diagnostics that find the real issue instead of selling a re-pipe."
      },
      {
        "t": "Water heaters",
        "d": "Sizing, install and warranty-backed tanks and tankless units."
      },
      {
        "t": "Sewer & repipes",
        "d": "Camera inspections and clear, quoted pricing before trenching starts."
      }
    ],
    "gallery": {
      "title": "The service gallery a plumber needs",
      "sub": "Work organized by job — real photos, scope notes and turnarounds at build.",
      "items": [
        "Emergency repair — same-day",
        "Water heater swap",
        "Drain line diagnostic",
        "Bathroom repipe plan"
      ]
    },
    "finance": {
      "title": "Prices, answered before the call",
      "sub": "A section that names pricing terms so cost questions never stall a service call.",
      "points": [
        "Flat-rate pricing per job",
        "Financing where offered",
        "Warranty details on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Charlotte, NC review.)",
    "proofLine": "This is a concept homepage for Tim Breault Plumbing. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "johana-s-professional-cleaning-services",
    "name": "Johana's Professional Cleaning Services",
    "industry": "Cleaning",
    "area": "Charlotte, NC",
    "phone": "(704) 299-7404",
    "phoneLink": "tel:+17042997404",
    "brand": {
      "dark": "#0f2a22",
      "mid": "#1c4a3c",
      "accent": "#4fdcae",
      "accent2": "#f2c14e",
      "light": "#eff7f3"
    },
    "kicker": "Charlotte North Carolina cleaning on a schedule you can rely on",
    "headline": "A clean home, on a schedule that holds",
    "sub": "A bare one-pager with a personal gmail is nearly the entire web presence for a cleaning business. This concept gives Johana a booking-first homepage with plan pricing, deep-clean offers and trust that matches the work.",
    "heroTags": [
      "Same cleaner",
      "Bonded & insured",
      "5.0-rated"
    ],
    "ctaPrimary": {
      "label": "Call (704) 299-7404",
      "href": "tel:+17042997404"
    },
    "trust": [
      {
        "n": "Charlotte",
        "l": "NC"
      },
      {
        "n": "Recurring",
        "l": "plans"
      },
      {
        "n": "Deep",
        "l": "cleans"
      },
      {
        "n": "Online",
        "l": "booking"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Recurring plans",
        "d": "Weekly, bi-weekly or monthly plans with the same trusted cleaner every visit."
      },
      {
        "t": "Deep cleans",
        "d": "Move-in, move-out and seasonal deep cleans booked online in minutes."
      },
      {
        "t": "Move-out / move-in",
        "d": "Tenant-turnover cleans on a schedule landlords can actually rely on."
      },
      {
        "t": "Commercial",
        "d": "Offices and storefronts cleaned after hours on a fixed plan."
      }
    ],
    "gallery": {
      "title": "The trust section a cleaner needs",
      "sub": "Before / after rooms organized by service — real photos and checklists at build.",
      "items": [
        "Weekly plan — kitchen & baths",
        "Move-out deep clean",
        "Deep clean before/after",
        "Commercial after-hours"
      ]
    },
    "finance": {
      "title": "Pricing that says what it costs",
      "sub": "A section that states rates up front so a quote never has to be a phone call.",
      "points": [
        "Flat per-visit or monthly pricing",
        "First-visit guarantee",
        "Holds & move-out specials"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Charlotte, NC review.)",
    "proofLine": "This is a concept homepage for Johana's Professional Cleaning Services. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "munoz-tree-services",
    "name": "Munoz Tree Services",
    "industry": "Tree Service",
    "area": "Dallas, TX",
    "phone": "972-302-5866",
    "phoneLink": "tel:+19723025866",
    "brand": {
      "dark": "#231420",
      "mid": "#382338",
      "accent": "#d0617d",
      "accent2": "#e8ae7a",
      "light": "#faf4f3"
    },
    "kicker": "Dallas Texas tree care with cleanup included",
    "headline": "Trimmed safe, removed clean, priced first",
    "sub": "A minimal gmail page makes tree work look casual — even when the crew is fully licensed and insured. This concept gives Munoz a price-in-writing homepage, a storm-response call button and a gallery where cleanup is visibly included.",
    "heroTags": [
      "Cleanup included",
      "Insured crews",
      "Storm response"
    ],
    "ctaPrimary": {
      "label": "Call 972-302-5866",
      "href": "tel:+19723025866"
    },
    "trust": [
      {
        "n": "Dallas",
        "l": "trees"
      },
      {
        "n": "Cleanup",
        "l": "included"
      },
      {
        "n": "Insured",
        "l": "crew"
      },
      {
        "n": "Storm",
        "l": "response"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Tree removal",
        "d": "Safe removals with cleanup to the stump you approve."
      },
      {
        "t": "Trimming & pruning",
        "d": "Structural pruning that keeps trees healthy and homes safe."
      },
      {
        "t": "Storm response",
        "d": "After-storm clearance prioritized for blocked driveways and roofs."
      },
      {
        "t": "Stump grinding",
        "d": "Ground below grade and seeded so there is no hole to remember."
      }
    ],
    "gallery": {
      "title": "The work album a tree site needs",
      "sub": "Removals and trims documented by job — real photos and cleanup at build.",
      "items": [
        "Removal with cleanup",
        "Canopy thinning",
        "Storm response — drive clear",
        "Stump grind"
      ]
    },
    "finance": {
      "title": "Quoted before the saw starts",
      "sub": "A section that answers price questions before anyone books.",
      "points": [
        "Flat price before the saw starts",
        "Cleanup included in the quote",
        "Insurance proof on request"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Dallas, TX review.)",
    "proofLine": "This is a concept homepage for Munoz Tree Services. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "medrano-s-painting",
    "name": "Medrano's Painting",
    "industry": "Painting",
    "area": "Austin, TX",
    "phone": "(512) 789-4240",
    "phoneLink": "tel:+15127894240",
    "brand": {
      "dark": "#0d1f2d",
      "mid": "#1a3a52",
      "accent": "#4a7ea8",
      "accent2": "#e2a84b",
      "light": "#f1f5f8"
    },
    "kicker": "Austin Texas painting, quoted before the first coat",
    "headline": "A finish that looks done by a crew, not rolled by one",
    "sub": "Painting sells on finish proof, and the current page has almost none. This concept gives Medrano a gallery-led homepage with itemized quotes, prep included and interior/exterior pages that rank locally.",
    "heroTags": [
      "Prep included",
      "Itemized quotes",
      "Cleanup done"
    ],
    "ctaPrimary": {
      "label": "Call (512) 789-4240",
      "href": "tel:+15127894240"
    },
    "trust": [
      {
        "n": "Austin",
        "l": "local"
      },
      {
        "n": "Itemized",
        "l": "quotes"
      },
      {
        "n": "Prep",
        "l": "included"
      },
      {
        "n": "Before",
        "l": "/after"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Interior painting",
        "d": "Two-coat consistency, cut in clean, and a walkthrough before the last check clears."
      },
      {
        "t": "Exterior painting",
        "d": "Prep-first exterior repaints with the right coatings for local weather."
      },
      {
        "t": "Cabinet & trim",
        "d": "Refinishing and cabinet repaint that look factory, not brushed."
      },
      {
        "t": "Drywall repair",
        "d": "Holes, patches and texture matched before a single coat goes on."
      }
    ],
    "gallery": {
      "title": "The finish gallery a painter needs",
      "sub": "Interior and exterior jobs documented by project — real photos and prep detail at build.",
      "items": [
        "Exterior full repaint",
        "Interior color transition",
        "Cabinet refinish close-up",
        "Drywall-repair finish"
      ]
    },
    "finance": {
      "title": "Quoted before the first coat",
      "sub": "A section that states terms so budget questions never stop an enquiry.",
      "points": [
        "Itemized estimate before work",
        "Prep included in the quote",
        "Paint brands stated up front"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Austin, TX review.)",
    "proofLine": "This is a concept homepage for Medrano's Painting. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "hunter-sprinklers",
    "name": "Hunter Sprinklers",
    "industry": "Irrigation",
    "area": "Cedar Park, TX",
    "phone": "512-690-3113",
    "phoneLink": "tel:+15126903113",
    "brand": {
      "dark": "#13280f",
      "mid": "#214619",
      "accent": "#8bc34a",
      "accent2": "#f2a65a",
      "light": "#f4f7ef"
    },
    "kicker": "Cedar Park Texas irrigation, scoped and quoted first",
    "headline": "Water where it is supposed to go, on a schedule that saves",
    "sub": "An AOL-era page that barely renders is doing nothing for an irrigation business. This concept gives Hunter a modern homepage: leak-repair section that answers the high-bill question, smart-controller savings and a yard visit quote flow.",
    "heroTags": [
      "Zone design",
      "Leak repair",
      "Smart savings"
    ],
    "ctaPrimary": {
      "label": "Call 512-690-3113",
      "href": "tel:+15126903113"
    },
    "trust": [
      {
        "n": "Cedar",
        "l": "Park"
      },
      {
        "n": "Leak",
        "l": "repair"
      },
      {
        "n": "Smart",
        "l": "savings"
      },
      {
        "n": "Scoped",
        "l": "quotes"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "System install",
        "d": "Zoned irrigation designed to the yard, not bolted onto a template."
      },
      {
        "t": "Repair & leaks",
        "d": "Solenoids, valves, heads and line breaks found and fixed."
      },
      {
        "t": "Smart controllers",
        "d": "WiFi controllers set to the local watering schedule for real savings."
      },
      {
        "t": "Winterization",
        "d": "Blow-outs and spring startups on a plan so nothing freezes."
      }
    ],
    "gallery": {
      "title": "The install gallery an irrigation co needs",
      "sub": "Systems documented by project — real photos, zones and service notes at build.",
      "items": [
        "New system install",
        "Zone/solenoid repair",
        "Smart controller setup",
        "Drip line refresh"
      ]
    },
    "finance": {
      "title": "Scoped, quoted, in writing",
      "sub": "A section that answers cost questions before the first trench.",
      "points": [
        "Site-visit scope before pricing",
        "Itemized written quote",
        "Seasonal plans available"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Cedar Park, TX review.)",
    "proofLine": "This is a concept homepage for Hunter Sprinklers. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "bexar-garage-doors",
    "name": "Bexar Garage Doors",
    "industry": "Garage Doors",
    "area": "San Antonio, TX",
    "phone": "(210) 307-4398",
    "phoneLink": "tel:+12103074398",
    "brand": {
      "dark": "#26120f",
      "mid": "#40201a",
      "accent": "#dd6b3f",
      "accent2": "#f0c987",
      "light": "#f8f2ea"
    },
    "kicker": "San Antonio Texas garage doors, serviced same-day",
    "headline": "Doors that open, repaired the same day",
    "sub": "An inactive template with a gmail address gives San Antonio door customers nothing to book. This concept gives Bexar a working homepage: 24/7 door-locked button, same-day booking and an install gallery that answers the price question.",
    "heroTags": [
      "Same-day repair",
      "Written quotes",
      "5.0-rated"
    ],
    "ctaPrimary": {
      "label": "Call (210) 307-4398",
      "href": "tel:+12103074398"
    },
    "trust": [
      {
        "n": "San",
        "l": "Antonio"
      },
      {
        "n": "24/7",
        "l": "door-locked"
      },
      {
        "n": "Same-day",
        "l": "repair"
      },
      {
        "n": "Written",
        "l": "quotes"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Garage door repair",
        "d": "Cables, springs, rollers and openers repaired same-day where possible."
      },
      {
        "t": "New door installs",
        "d": "Sightline and material guidance with a clean, warrantied install."
      },
      {
        "t": "Opener service",
        "d": "Programming and repair across all major motor brands."
      },
      {
        "t": "Emergency service",
        "d": "Stuck-door and security repair when the door will not close or open."
      }
    ],
    "gallery": {
      "title": "The install gallery a door site needs",
      "sub": "Doors and repairs documented by job — real photos and warranties at build.",
      "items": [
        "Spring & cable service",
        "New door install",
        "Opener programming",
        "Emergency door repair"
      ]
    },
    "finance": {
      "title": "Pricing, on the record",
      "sub": "A section that states terms so a door quote never surprises anyone.",
      "points": [
        "Same-day quotes where possible",
        "Written price before install",
        "Warranty on parts & labor"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real San Antonio, TX review.)",
    "proofLine": "This is a concept homepage for Bexar Garage Doors. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "manny-pool-services",
    "name": "Manny Pool Services",
    "industry": "Pool Cleaning",
    "area": "Miami, FL",
    "phone": "786-609-4328",
    "phoneLink": "tel:+17866094328",
    "brand": {
      "dark": "#102324",
      "mid": "#1d3d3e",
      "accent": "#66d9cf",
      "accent2": "#ef9d5a",
      "light": "#eff6f5"
    },
    "kicker": "Miami Florida pool care on a fixed plan",
    "headline": "A clean pool, on a fixed weekly plan",
    "sub": "A one-pager with a gmail address undersells Miami-area pool care. This concept gives Manny plan pricing on the homepage, a green-to-clear rescue section and a before/after gallery that makes the weekly plan feel obvious.",
    "heroTags": [
      "Weekly service",
      "Flat monthly",
      "Green-to-clear"
    ],
    "ctaPrimary": {
      "label": "Call 786-609-4328",
      "href": "tel:+17866094328"
    },
    "trust": [
      {
        "n": "Miami",
        "l": "pools"
      },
      {
        "n": "Weekly",
        "l": "plans"
      },
      {
        "n": "Green",
        "l": "-to-clear"
      },
      {
        "n": "Flat",
        "l": "monthly"
      }
    ],
    "servicesTitle": "Plans the rebuilt site sells",
    "services": [
      {
        "t": "Weekly service",
        "d": "Consistent chemistry, brushing and filtering on a fixed repeat visit."
      },
      {
        "t": "Green pools",
        "d": "Green-to-clear recovery programs priced before the first shock."
      },
      {
        "t": "Repairs & equipment",
        "d": "Pumps, filters and heaters diagnosed and quoted before work starts."
      },
      {
        "t": "Seasonal open/close",
        "d": "Spring opens and winter closes on a schedule you can rely on."
      }
    ],
    "gallery": {
      "title": "The clean-pool gallery that sells it",
      "sub": "Pools documented before and after service — real photos and care notes at build.",
      "items": [
        "Weekly service — before/after",
        "Green-to-clear rescue",
        "Tile & waterline detail",
        "Equipment room refresh"
      ]
    },
    "finance": {
      "title": "Plan pricing, on the record",
      "sub": "A section that shows monthly costs so the budget question never stops a signup.",
      "points": [
        "Flat monthly plan pricing",
        "No long-term lock-in",
        "Equipment repairs quoted first"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Miami, FL review.)",
    "proofLine": "This is a concept homepage for Manny Pool Services. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "mr-roland-pest-control-llc",
    "name": "Mr Roland Pest Control LLC",
    "industry": "Pest Control",
    "area": "Orlando, FL",
    "phone": "407-577-8750",
    "phoneLink": "tel:+14075778750",
    "brand": {
      "dark": "#12212e",
      "mid": "#1f3a4c",
      "accent": "#6fd3e0",
      "accent2": "#f2a65a",
      "light": "#eef4f6"
    },
    "kicker": "Orlando Florida pest control with a real phone line",
    "headline": "Pests handled, exclusions sealed, no games",
    "sub": "A minimal page with a gmail address makes pest control look part-time. This concept gives Mr Roland plan pricing on the homepage, warranty-backed treatment pages and a phone-first layout that turns reviews into calls.",
    "heroTags": [
      "Warranty-backed",
      "Same-day visits",
      "Specialist work"
    ],
    "ctaPrimary": {
      "label": "Call 407-577-8750",
      "href": "tel:+14075778750"
    },
    "trust": [
      {
        "n": "Orlando",
        "l": "local"
      },
      {
        "n": "Plan",
        "l": "pricing"
      },
      {
        "n": "Warranty",
        "l": "-backed"
      },
      {
        "n": "Phone",
        "l": "-first"
      }
    ],
    "servicesTitle": "Coverage the rebuilt site leads with",
    "services": [
      {
        "t": "General pest control",
        "d": "Scheduled treatments for ants, roaches, spiders and rodents."
      },
      {
        "t": "Bee / wasp removal",
        "d": "Specialist extraction and exclusion, documented and warrantied."
      },
      {
        "t": "Termite protection",
        "d": "Inspection, treatment and barrier plans with straightforward pricing."
      },
      {
        "t": "Rodent exclusion",
        "d": "Find the entry point, seal it, then trap — not just bait-and-rinse."
      }
    ],
    "gallery": {
      "title": "The proof section a pest site needs",
      "sub": "Treatments documented by job — real photos and warranties at build.",
      "items": [
        "Monthly general plan",
        "Bee extraction & exclusion",
        "Rodent exclusion report",
        "Termite barrier install"
      ]
    },
    "finance": {
      "title": "Plans and prices, on the table",
      "sub": "A section that shows plans and terms so nobody has to ask what a treatment costs.",
      "points": [
        "Free estimates with no fine print",
        "Warranty-backed treatments",
        "Seasonal plans on a fixed schedule"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Orlando, FL review.)",
    "proofLine": "This is a concept homepage for Mr Roland Pest Control LLC. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "mile-high-junk-llc",
    "name": "Mile High Junk LLC",
    "industry": "Junk Removal",
    "area": "Aurora, CO",
    "phone": "(720) 636-4656",
    "phoneLink": "tel:+17206364656",
    "brand": {
      "dark": "#272010",
      "mid": "#42371c",
      "accent": "#eec062",
      "accent2": "#e0785a",
      "light": "#f9f6ec"
    },
    "kicker": "Aurora Colorado junk removal at a fixed price",
    "headline": "Gone today, priced before the truck rolls",
    "sub": "Junk removal is a price-first decision and the current page hides every number. This concept gives Mile High a price-it-before-the-truck homepage, cleanout booking and a gallery that proves the truck shows up.",
    "heroTags": [
      "Fixed pricing",
      "Same-week pickup",
      "Estate cleanouts"
    ],
    "ctaPrimary": {
      "label": "Call (720) 636-4656",
      "href": "tel:+17206364656"
    },
    "trust": [
      {
        "n": "Aurora",
        "l": "CO"
      },
      {
        "n": "Price",
        "l": "-first"
      },
      {
        "n": "Same-week",
        "l": "pickup"
      },
      {
        "n": "Cleanouts",
        "l": "handled"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Full-home cleanouts",
        "d": "Whole-house, garage, estate and hoarding cleanouts done ethically and completely."
      },
      {
        "t": "Furniture & appliance",
        "d": "Single-item pickups that disappear within the week."
      },
      {
        "t": "Construction debris",
        "d": "Post-reno and build-site hauling with the dump runs handled."
      },
      {
        "t": "Recurring hauling",
        "d": "Subscription pickup routes for busy properties."
      }
    ],
    "gallery": {
      "title": "The clear-out gallery that proves it",
      "sub": "Jobs photographed before and after — real loads and clean gut-outs at build.",
      "items": [
        "Full-home cleanout",
        "Garage liberation",
        "Furniture pickup day",
        "Construction debris run"
      ]
    },
    "finance": {
      "title": "One price, before the truck rolls",
      "sub": "A section that answers the cost question before anyone has to call.",
      "points": [
        "Quote before any truck rolls",
        "Single flat price for the load",
        "No hidden dump fees"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Aurora, CO review.)",
    "proofLine": "This is a concept homepage for Mile High Junk LLC. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "yanni-electric-llc",
    "name": "Yanni Electric LLC",
    "industry": "Electrical",
    "area": "Aurora, CO",
    "phone": "303-908-6195",
    "phoneLink": "tel:+13039086195",
    "brand": {
      "dark": "#12212e",
      "mid": "#1f3a4c",
      "accent": "#6fd3e0",
      "accent2": "#f2a65a",
      "light": "#eef4f6"
    },
    "kicker": "Aurora Colorado licensed electrical work, quoted in writing",
    "headline": "Wired to code, quoted before the panel opens",
    "sub": "A single gmail page for an electrical company is a trust gap — homeowners need license and scope proof. This concept gives Yanni license-and-insurance proof on the homepage, EV and panel pages that rank, and a written-quote flow.",
    "heroTags": [
      "Licensed",
      "Written quotes",
      "Code-safe"
    ],
    "ctaPrimary": {
      "label": "Call 303-908-6195",
      "href": "tel:+13039086195"
    },
    "trust": [
      {
        "n": "Aurora",
        "l": "CO"
      },
      {
        "n": "Licensed",
        "l": "shown"
      },
      {
        "n": "EV",
        "l": "chargers"
      },
      {
        "n": "Written",
        "l": "quotes"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Panel & code repair",
        "d": "Upgrades and safety fixes brought up to current code, documented."
      },
      {
        "t": "EV chargers",
        "d": "Load-calculated charger installs with rebate-friendly paperwork."
      },
      {
        "t": "Lighting & outlets",
        "d": "Indoor and outdoor additions planned and quoted in writing."
      },
      {
        "t": "Troubleshooting",
        "d": "Flickers, dead circuits and overloads traced to the actual cause."
      }
    ],
    "gallery": {
      "title": "The work gallery an electrician needs",
      "sub": "Installations and repairs documented by job — real photos and code notes at build.",
      "items": [
        "Panel upgrade",
        "EV charger install",
        "Code-safety repair",
        "Lighting / outdoor install"
      ]
    },
    "finance": {
      "title": "Licensed, quoted, insured",
      "sub": "A section that shows licensing and pricing terms before the call.",
      "points": [
        "License number shown up front",
        "Written quotes before work",
        "Workmanship backed in writing"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Aurora, CO review.)",
    "proofLine": "This is a concept homepage for Yanni Electric LLC. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "ecoshine",
    "name": "EcoShine",
    "industry": "Pressure Washing",
    "area": "Denver, CO",
    "phone": "(720) 357-4332",
    "phoneLink": "tel:+17203574332",
    "brand": {
      "dark": "#241714",
      "mid": "#3a2a22",
      "accent": "#c96f4a",
      "accent2": "#e3b778",
      "light": "#f7f2ea"
    },
    "kicker": "Denver Colorado pressure washing, flat rate per surface",
    "headline": "Clean like it was day one",
    "sub": "A placeholder page with a gmail address means the brand does not exist online yet. This concept gives EcoShine a before/after-first homepage, quote-from-photos flow and local service pages that put the brand on the map.",
    "heroTags": [
      "Flat rate",
      "Soft-wash safe",
      "Insured"
    ],
    "ctaPrimary": {
      "label": "Call (720) 357-4332",
      "href": "tel:+17203574332"
    },
    "trust": [
      {
        "n": "Denver",
        "l": "brand"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Quote",
        "l": "from photos"
      },
      {
        "n": "Soft-wash",
        "l": "safe"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Driveway & walkways",
        "d": "Cleaning that makes the approach look new again."
      },
      {
        "t": "House / siding washing",
        "d": "Soft-wash methods that protect paint and windows."
      },
      {
        "t": "Roof cleaning",
        "d": "Mildew and staining removal without pressure damage."
      },
      {
        "t": "Paver sealing",
        "d": "Clean first, then seal — so it stays looking sold."
      }
    ],
    "gallery": {
      "title": "The before/after reel that sells it",
      "sub": "Surfaces cleaned and sealed — real before/after sets at build.",
      "items": [
        "Driveway reveal",
        "Siding soft-wash",
        "Roof stain removal",
        "Paver seal — before/after"
      ]
    },
    "finance": {
      "title": "Flat rate, quoted from photos",
      "sub": "A section that answers the cost question before the first phone call.",
      "points": [
        "Flat rate per surface",
        "Quote from photos, in writing",
        "Satisfaction touch-up pass"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Denver, CO review.)",
    "proofLine": "This is a concept homepage for EcoShine. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  },
  {
    "slug": "innovative-contracting-services-llc",
    "name": "Innovative Contracting Services LLC",
    "industry": "Fence & Deck",
    "area": "Denver, CO",
    "phone": "720-227-6370",
    "phoneLink": "tel:+17202276370",
    "brand": {
      "dark": "#272010",
      "mid": "#42371c",
      "accent": "#eec062",
      "accent2": "#e0785a",
      "light": "#f9f6ec"
    },
    "kicker": "Denver Colorado fences & decks, measured and quoted first",
    "headline": "Measured right, quoted in writing, built to last",
    "sub": "Fence and deck work sells on real projects, and the current page shows almost none. This concept gives Innovative a measure-first quote flow, a build gallery with before/after and material pages that answer cost questions.",
    "heroTags": [
      "Measured quotes",
      "Wood + vinyl",
      "Built to last"
    ],
    "ctaPrimary": {
      "label": "Call 720-227-6370",
      "href": "tel:+17202276370"
    },
    "trust": [
      {
        "n": "Denver",
        "l": "builds"
      },
      {
        "n": "Measured",
        "l": "quotes"
      },
      {
        "n": "Before",
        "l": "/after"
      },
      {
        "n": "Wood",
        "l": "+ vinyl"
      }
    ],
    "servicesTitle": "Services the rebuilt site sells",
    "services": [
      {
        "t": "Fence install",
        "d": "Privacy, wood, vinyl and aluminum — measured, quoted and set in writing."
      },
      {
        "t": "Deck build",
        "d": "Framing through finish, with material and span choices priced up front."
      },
      {
        "t": "Gates & repairs",
        "d": "Sagging gates, broken rails and rotted posts brought back to solid."
      },
      {
        "t": "Stain & seal",
        "d": "Prep, stain and seal so the build keeps its finish for seasons."
      }
    ],
    "gallery": {
      "title": "The build gallery a fence co needs",
      "sub": "Fences and decks documented by project — real photos and material notes at build.",
      "items": [
        "Privacy fence install",
        "Deck build + finish",
        "Gate install detail",
        "Stain / seal refresh"
      ]
    },
    "finance": {
      "title": "Measured, quoted, in writing",
      "sub": "A section that answers cost and material questions before the first post.",
      "points": [
        "On-site measure before quoting",
        "Material grade itemized",
        "Written contract with terms"
      ]
    },
    "booking": true,
    "bookingTitle": "Get a fixed-price quote",
    "bookingSub": "In the real build, one form routes straight to your phone or calendar.",
    "testimonial": "The first page finally matches how the work is done. (Placeholder for a real Denver, CO review.)",
    "proofLine": "This is a concept homepage for Innovative Contracting Services LLC. It shows the structure and feel a rebuild can have; your real photos, brand and numbers go in at build time."
  }
];
